FROM public.ecr.aws/lambda/python:3.8

COPY ./src /var/lang/lib/python3.8/site-packages

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "main.handler" ]
