FROM python:3.9.2-buster
COPY . ./inqdo_tools


# WORKDIR /usr/src/app

# COPY requirements/api.txt requirements/setup.cfg ./

# RUN python3 -m ensurepip
# RUN pip install --no-cache --upgrade pip setuptools
# RUN pip install -r api.txt
# RUN pip install inqdo_tools/src
# RUN rm -rf inqdo_tools

# ENV PYTHONPATH "${PYTHONPATH}:/usr/src/app/src"

# EXPOSE 8000
# CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
