FROM public.ecr.aws/lambda/python:3.8

# Copy function code
COPY . ${LAMBDA_TASK_ROOT}

COPY requirements-dev.txt ${LAMBDA_TASK_ROOT}
RUN pip install -r requirements-dev.txt

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "main.handler" ]
